### PR TITLE
Support Ruby 3.x and various updates

### PR DESCRIPTION
**Pull request by yano3**
Add some changes to support Ruby 3.x.

- Add `rexml` to dependency.
- Update Docker base image.
- Migrate deprecated bundler options.

Fix many vulnerabilities.

- Update gems.
- Update OS packages in Docker image when building.

### CODE REVIEW

**Comment by yano3** [comment]
@hypermkt Hi! Review please.

**Comment by hypermkt** [comment]
ohhhh, Sorry I didn't notice your pull request! I am going to see this PR now!

**Comment by hypermkt** [comment]
In Ruby 3.1.0, I cloud notify to Slack!

```
$ ruby -v
ruby 3.1.0p0 (2021-12-25 revision fb4df44d16) [x86_64-darwin21]
$ export SLACK_ICON_EMOJI=:erutaso:
$ export SLACK_USERNAME=千反田える
$ export SLACK_CHANNEL=#develop
$ export SLACK_INCOMING_WEBHOOK_URL={snip}
$ bundle exec ruby bin/chitanda-san.rb
```

image

**Review by hypermkt — APPROVED** [review]
LGTM~~~~!

**Comment by yano3** [comment]
Thanks!

**Pull request merged**
